Project Bobrov, Suvorov
kajigor/fl-2021-hse-win pull request #143
Opened 2021-10-11 18:02 UTC by slawa4s

2021-10-13 10:20 UTC, kajigor commented
* Как выразить эпсилон правило? 
* Было бы неплохо получить более информативные ошибки, чем просто `Syntax Error` [paren.txt](https://github.com/kajigor/fl-2021-hse-win/files/7337163/paren.txt)
* Описание конкретного синтаксиса говорит, что вокруг операторов должны быть пробелы, при этом [aa.txt](https://github.com/kajigor/fl-2021-hse-win/files/7337226/aa.txt) успешно парсится. 
* Саблайм предлагает странные варианты автодополнения: то нетерминалы, которые определены в соседних файлах, но нетерминалы из этого файла не предлагает.

2021-10-16 04:40 UTC, kajigor requested changes
Вообще довольно неплохо, но надо еще мелочи поправить.

2021-10-16 04:40 UTC, kajigor commented on Parser/parse.py
>  def p_error(p):
Скорее вот в этой функции надо менять сообщение об ошибке.

2021-10-16 04:40 UTC, kajigor commented on Parser/parse.py
>  def p_error(p):
В смысле тут добавить информацию о том, на каком символе что-то пошло не так.

2021-10-16 04:40 UTC, kajigor commented on Parser/parse.py
> +        p[0] = Node("()", [p[2]], parser.my_result.num_of_nodes)
А вот это зачем? АСД уже и так показывает, где скобки в выражениях.

2021-10-16 08:39 UTC, slawa4s commented on Parser/parse.py
>  def p_error(p):
А как я могу получить символ, если лексер не токенизировал?

2021-10-16 08:43 UTC, slawa4s commented on Parser/parse.py
>  def p_error(p):
Я не очень понял. Ведь в p[1] и p[2] хранится конкретный символ или ID на котором что-то пошло не так

2021-10-16 08:53 UTC, slawa4s commented on Parser/parse.py
>  def p_error(p):
Надо вывести номр символа или символ? Символ я вроде вывожу, так как в operations хранится либо символ, либо ID и имя.

2021-10-16 08:56 UTC, slawa4s commented on Parser/parse.py
>  def p_error(p):
Я не очень понимаю, как можно вывести номер символа, если лексер токенезацию не проводил

2021-10-16 10:41 UTC, kajigor commented on Parser/parse.py
>  def p_error(p):
Я про p_error

2021-10-18 15:02 UTC, kajigor commented
Тут остался доклад

2021-10-20 12:50 UTC, kajigor commented
Какие приоритеты и ассоциативность у бинарных операций, кстати?

2021-10-20 16:07 UTC, slawa4s commented
Все операторы правоассоциативны

Приоритеты операторов: 1) Скобки; 2) Повторение, опциональный оператор; 3) Конкатенация; 4) Альтернатива

2021-10-20 16:59 UTC, kajigor commented
В реализации приоритеты не соблюдаются: 
[aa.txt](https://github.com/kajigor/fl-2021-hse-win/files/7383043/aa.txt)
![aa txt graph](https://user-images.githubusercontent.com/1614576/138137973-5f64b385-1610-4aa4-8896-a3faa5c4e0b1.png)
[bb.txt](https://github.com/kajigor/fl-2021-hse-win/files/7383044/bb.txt)
![bb txt graph](https://user-images.githubusercontent.com/1614576/138137976-4f347780-9778-43d4-87ba-41c4da0f983c.png)

2021-10-20 18:18 UTC, slawa4s commented
Изменили приоритет

2021-10-21 05:27 UTC, kajigor commented
Ок, зачла

2021-10-21 05:27 UTC, closed without merging